function test_mava_feature_parameter_screen
% Initial parameter screen must produce usable feature signatures.

repo_root = fullfile(fileparts(mfilename('fullpath')), '..', '..');
addpath(genpath(fullfile(repo_root, 'Code', 'System')));
addpath(fullfile(repo_root, 'Code', 'Fitting', 'mava_codex'));
out_dir = tempname;
mkdir(out_dir);
cleanup = onCleanup(@() rmdir(out_dir, 's')); %#ok<NASGU>

result = mava_feature_parameter_screen(out_dir, ...
    'ParameterNames', {'k_1'}, 'FoldLevels', [0.5 1 2]);
assert(height(result.responses) == 2 * 3 * 14, ...
    'Screen must contain primary and validation features for each trial.');
assert(all(ismember(["Control"; "H251N"], result.summary.genotype)), ...
    'Screen summary is missing a condition.');
assert(all(result.responses.parameter == "k_1"), ...
    'Screen included an unexpected parameter.');
assert(~any(result.summary.parameter == "k_2"), ...
    'k_2 must never enter a free-parameter screen.');
assert(isfile(fullfile(out_dir, 'feature_responses.csv')) && ...
    isfile(fullfile(out_dir, 'parameter_screen_summary.csv')) && ...
    isfile(fullfile(out_dir, 'signature_correlations.csv')) && ...
    isfile(fullfile(out_dir, 'stage_recommendations.csv')), ...
    'Screen did not materialize all selection artifacts.');
fprintf('PASS: Mava feature parameter screen\n');
end
