function test_build_mava_sequential_fit_config
% Sequential configs must preserve nesting, bounds, settings, and isolation.

repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repo_root, 'Code', 'System')));
addpath(fullfile(repo_root, 'Code', 'Fitting', 'mava_codex'));
run_dir = tempname;
mkdir(run_dir);
cleanup = onCleanup(@() rmdir(run_dir, 's')); %#ok<NASGU>

settings = struct('fit_start_index', 481, 'max_fun_evals', 37, ...
    'tol_fun', 2e-6, 'tol_x', 3e-4, ...
    'figure_current_fit', 0, 'figure_optimization_progress', 0);
stages = mava_parameter_stages();

[control_file, control_record] = build_mava_sequential_fit_config( ...
    run_dir, 'shared_by_genotype', 'Control', stages(1), 1, [], settings);
control = loadjson(control_file).MyoSim_optimization;
assert(strcmp(control_file, fullfile(run_dir, 'configs', ...
    'shared_by_genotype__Control__k123__s01.json')), ...
    'Control config path is not the required unique capsule path.');
assert(strcmp(control.best_model_folder, fullfile(run_dir, 'results', ...
    'shared_by_genotype', 'Control', 'k123', 's01')), ...
    'Control result path is not the required unique capsule path.');
assert(isfolder(control.best_model_folder), ...
    'The result directory must exist before a fit starts.');
assert(strcmp(control_record.config_file, control_file) && ...
    strcmp(control_record.result_dir, control.best_model_folder), ...
    'The returned record must identify the written config and result directory.');
assert(strcmp(control.model_template_file_string, fullfile(repo_root, ...
    'Code', 'Fitting', 'twitch_6state_control', 'temp', 'best', ...
    'model_best.json')), 'Control must use its Before best-fit model.');
assert(strcmp(control.job{1}.options_file_string, fullfile(repo_root, ...
    'Code', 'Fitting', 'twitch_6state_control', 'sim_input', ...
    'sim_options.json')), 'Control must use its own simulation options.');
assert(strcmp(control.job{1}.target_file_string, fullfile(run_dir, 'data', ...
    'shared_by_genotype', 'ctrl_acute_target.txt')), ...
    'Control must map to the acute Control target.');
assert(strcmp(control.job{1}.protocol_file_string, fullfile(run_dir, 'data', ...
    'shared_by_genotype', 'ctrl_acute_protocol.txt')), ...
    'Control protocol must come from its alignment data directory.');
assert_config_contract(control, {'k_1','k_2','k_3'}, ...
    [0.5 0.5 0.5], settings);
assert_baseline_bounds(control, control.model_template_file_string);

previous_best = [0.11 0.22 0.33];
[ind_file, ind_record] = build_mava_sequential_fit_config( ...
    run_dir, 'independent_trace', 'Control', stages(2), 1, ...
    previous_best, settings);
independent = loadjson(ind_file).MyoSim_optimization;
assert_config_contract(independent, ...
    {'k_1','k_2','k_3','k_5_0'}, [previous_best 0.5], settings);
assert_baseline_bounds(independent, independent.model_template_file_string);
assert(strcmp(ind_record.alignment_policy, 'independent_trace') && ...
    strcmp(ind_record.genotype, 'Control') && ...
    strcmp(ind_record.stage, 'plus_k50') && ind_record.restart == 1, ...
    'The returned record must retain the fit identity.');

[hcm_file, hcm_record] = build_mava_sequential_fit_config( ...
    run_dir, 'shared_by_genotype', 'H251N', 'plus_k73', 2, [], settings);
hcm = loadjson(hcm_file).MyoSim_optimization;
expected_hcm_start = ...
    [0.57082039325 0.219348530672 0.467876668094 ...
     0.716404805516 0.364932942938 0.61346108036];
assert_config_contract(hcm, ...
    {'k_1','k_2','k_3','k_5_0','k_4_0','k_7_3'}, ...
    expected_hcm_start, settings);
assert_baseline_bounds(hcm, hcm.model_template_file_string);
assert(strcmp(hcm.model_template_file_string, fullfile(repo_root, ...
    'Code', 'Fitting', 'twitch_6state_HCM', 'temp', 'best', ...
    'model_best.json')), 'H251N must use its Before best-fit model.');
assert(strcmp(hcm.job{1}.target_file_string, fullfile(run_dir, 'data', ...
    'shared_by_genotype', 'hcm_acute_target.txt')), ...
    'H251N must map to the acute H251N target.');
assert(strcmp(hcm_record.config_file, hcm_file), ...
    'H251N record must identify its config.');

assert(~strcmp(control_file, ind_file) && ~strcmp(ind_file, hcm_file) && ...
    ~strcmp(control.best_model_folder, independent.best_model_folder) && ...
    ~strcmp(independent.best_model_folder, hcm.best_model_folder), ...
    'Every fit config and result path must be unique.');

fprintf('PASS: sequential Mava fit config factory\n');
end

function assert_config_contract(opt, expected_names, expected_start, settings)
names = cellfun(@(p) p.name, opt.parameter, 'UniformOutput', false);
starts = cellfun(@(p) p.p_value, opt.parameter);
assert(isequal(names, expected_names), ...
    'Free parameter names or order do not match the requested stage.');
assert(max(abs(starts - expected_start)) < 1e-12, ...
    'Normalized start coordinates do not match the deterministic seed.');
assert(any(strcmp(names, 'k_2')), ...
    'Every sequential stage must keep k_2 independently free.');
assert(~isfield(opt, 'k_2_k_1_ratio'), ...
    'Independent-k_2 configs must not contain a ratio constraint.');
assert(opt.job{1}.fit_start_index == settings.fit_start_index, ...
    'The requested fit start row was not copied unchanged.');
assert(opt.max_fun_evals == settings.max_fun_evals && ...
    opt.tol_fun == settings.tol_fun && opt.tol_x == settings.tol_x && ...
    opt.figure_current_fit == settings.figure_current_fit && ...
    opt.figure_optimization_progress == settings.figure_optimization_progress, ...
    'Requested optimizer settings were not copied unchanged.');
end

function assert_baseline_bounds(opt, template_file)
base = loadjson(template_file);
base_parameters = base.MyoSim_model.hs_props.parameters;
for i = 1:numel(opt.parameter)
    p = opt.parameter{i};
    center = log10(base_parameters.(p.name));
    assert(strcmp(p.p_mode, 'log'), 'Sequential bounds must use log mode.');
    assert(abs(p.min_value - (center - 1)) < 1e-10 && ...
        abs(p.max_value - (center + 1)) < 1e-10, ...
        'Bounds must stay centered one log unit around the baseline model.');
end
end
