function test_run_mava_sequential_dry_run
% Dry runs must build a complete isolated 3x4x2 capsule without fitting.

repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repo_root, 'Code', 'System')));
addpath(fullfile(repo_root, 'Code', 'Fitting', 'mava_codex'));
output_root = tempname;
mkdir(output_root);
cleanup = onCleanup(@() remove_if_present(output_root));
run_id = sprintf('task5_dry_%s_%06d', char(datetime('now', ...
    'Format', 'yyyyMMdd''T''HHmmssSSS')), randi(999999));
production_root = fullfile(repo_root, 'Code', 'Fitting', 'mava_codex', ...
    'output');
production_before = directory_snapshot(production_root);

run = run_mava_sequential_analysis(run_id, 'dry_run', ...
    'output_root', output_root, 'restarts', 2, ...
    'max_fun_evals', 10);
run_dir = fullfile(output_root, run_id);
assert(strcmp(run.run_dir, run_dir) && isfolder(run_dir), ...
    'Dry run did not return and create the requested isolated capsule.');

manifest_file = fullfile(run_dir, 'manifest.json');
manifest = loadjson(manifest_file);
assert(strcmp(manifest.run_id, run_id) && ...
    strcmp(manifest.mode, 'dry_run') && ...
    strcmp(manifest.status, 'dry_run_complete'), ...
    'Dry run manifest identity or terminal status is wrong.');
assert(manifest.settings.fit_start_index == 481 && ...
    manifest.settings.restarts == 2 && ...
    manifest.settings.extra_final_restarts == 4 && ...
    manifest.settings.max_fun_evals == 10 && ...
    abs(manifest.settings.tol_fun - 1e-5) < eps && ...
    abs(manifest.settings.tol_x - 1e-3) < eps && ...
    strcmp(manifest.settings.scale_mode, 'peak'), ...
    'Dry run manifest omitted or changed requested/default controls.');
assert(isfield(manifest, 'repository_head') && ...
    numel(manifest.repository_head) == 40 && ...
    isfield(manifest, 'matlab_version') && ...
    isfield(manifest, 'created_at'), ...
    'Dry run manifest omitted environment provenance.');
assert(isfield(manifest.hashes, 'workbook') && ...
    isfield(manifest.hashes, 'protocol') && ...
    isfield(manifest.hashes, 'baseline_templates') && ...
    isfield(manifest.hashes, 'options') && ...
    numel(manifest.hashes.sources) >= 8, ...
    'Dry run manifest omitted required input or source hashes.');
source_paths = cellfun(@(item) item.path, manifest.hashes.sources, ...
    'UniformOutput', false);
required_sources = {'run_mava_sequential_analysis.m', ...
    'mava_run_manifest.m','mava_sha256.m','evaluate_single_trial.m'};
for i = 1:numel(required_sources)
    assert(any(cellfun(@(path) endsWith(path, required_sources{i}), ...
        source_paths)), 'Manifest omitted behavior-defining source %s.', ...
        required_sources{i});
end

assert(numel(manifest.groups) == 2, ...
    'Manifest must retain the two requested alignment groups.');
assert(strcmp(manifest.groups{1}.policy, 'shared_by_genotype') && ...
    isequal(manifest.groups{1}.genotypes, {'Control','H251N'}) && ...
    strcmp(manifest.groups{2}.policy, 'independent_trace') && ...
    isequal(manifest.groups{2}.genotypes, {'Control'}), ...
    'Manifest alignment groups are not the required three comparisons.');
expected_stage_ids = {'k123','plus_k50','plus_k40','plus_k73'};
assert(numel(manifest.stages) == 4 && ...
    isequal(cellfun(@(s) s.id, manifest.stages, ...
    'UniformOutput', false), expected_stage_ids), ...
    'Manifest stage IDs or order changed.');

inventory = manifest.inventory;
required = cellfun(@(item) item.required, inventory);
assert(numel(inventory) == 36 && sum(required) == 24 && ...
    sum(~required) == 12, ...
    ['Two-restart runs must declare 24 base records plus 12 optional ' ...
    'final-stage records without activating the extras.']);
assert(isempty(manifest.materialization.optional_final_restart_groups) && ...
    manifest.records_planned == 24, ...
    'Default planning must exclude optional final-stage restarts.');
for i = 1:numel(inventory)
    item = inventory{i};
    assert(isfield(item, 'alignment_policy') && ...
        isfield(item, 'genotype') && isfield(item, 'stage') && ...
        isfield(item, 'restart') && isfield(item, 'config_file') && ...
        isfield(item, 'result_dir') && isfield(item, 'seed_strategy') && ...
        isfield(item, 'seed') && isfield(item, 'parameter_names') && ...
        isfield(item, 'bounds'), ...
        'Manifest inventory omitted a required fit identity field.');
    assert(numel(item.bounds) == numel(item.parameter_names), ...
        'Each inventory record must fix one bound per free parameter.');
end
materialized = manifest.materialization.configs;
materialized_hashes = cellfun(@(item) item.sha256, materialized, ...
    'UniformOutput', false);
assert(sum(~cellfun(@isempty, materialized_hashes)) == 24, ...
    'Exactly the 24 base configs must be materialized by dry run.');
assert(all(cellfun(@(item) isfield(item, 'resolved_seed') && ...
    ~isempty(item.resolved_seed), materialized(logical(required)))), ...
    'Every materialized base config must record exact resolved seed coordinates.');
assert(all(cellfun(@(item) ~isempty(item.target_sha256) && ...
    ~isempty(item.protocol_sha256) && ~isempty(item.metrics_sha256), ...
    manifest.materialization.data_files)), ...
    'Every config-consumed target/protocol/metrics table must be hashed.');

assert(isfile(fullfile(run_dir, 'data', 'shared_by_genotype', ...
    'experimental_metrics.csv')) && ...
    isfile(fullfile(run_dir, 'data', 'independent_trace', ...
    'experimental_metrics.csv')), ...
    'Dry run did not preprocess every requested alignment policy.');

configs = dir(fullfile(run_dir, 'configs', '*.json'));
assert(numel(configs) == 24, ...
    'Two-restart dry run must create exactly 3 x 4 x 2 = 24 configs.');
assert(numel(unique({configs.name})) == 24, ...
    'Every dry-run config filename must be unique.');
for i = 1:numel(configs)
    config_path = fullfile(configs(i).folder, configs(i).name);
    loaded = loadjson(config_path);
    opt = loaded.MyoSim_optimization;
    names = cellfun(@(p) p.name, opt.parameter, 'UniformOutput', false);
    starts = cellfun(@(p) p.p_value, opt.parameter);
    inventory_index = find(cellfun(@(item) ...
        strcmp(item.config_file, config_path), inventory));
    assert(isscalar(inventory_index) && ...
        max(abs(starts - inventory{inventory_index}.dry_run_seed)) < 1e-12, ...
        'Manifest seed declaration does not match the materialized dry config.');
    assert(max(abs(starts - ...
        materialized{inventory_index}.resolved_seed)) < 1e-12, ...
        'Manifest materialization omitted the config''s exact resolved seed.');
    assert(any(strcmp(names, 'k_2')), ...
        'Each sequential config must contain ordinary free k_2.');
    assert(~isfield(opt, 'constraint') && ...
        ~isfield(opt, 'k_2_k_1_ratio'), ...
        'Sequential configs must not reintroduce a k_2 ratio constraint.');
    assert(opt.job{1}.fit_start_index == 481, ...
        'Every dry-run config must use row 481 as the first fit row.');
end

statuses = dir(fullfile(run_dir, 'results', '**', 'status.json'));
assert(numel(statuses) == 24, ...
    'Every planned result must have a status.json.');
for i = 1:numel(statuses)
    status = loadjson(fullfile(statuses(i).folder, statuses(i).name));
    assert(strcmp(status.status, 'planned'), ...
        'Dry-run result status must remain planned, not complete.');
end
fitted_models = dir(fullfile(run_dir, '**', 'model_best.json'));
assert(isempty(fitted_models), ...
    'Dry run must not create fitted model_best.json files.');

summarize_id = '';
try
    run_mava_sequential_analysis(run_id, 'summarize', ...
        'output_root', output_root, 'restarts', 2, ...
        'max_fun_evals', 10);
catch ME
    summarize_id = ME.identifier;
end
assert(strcmp(summarize_id, ...
    'run_mava_sequential_analysis:runNotSummarizable'), ...
    'Dry-run capsules must be rejected before Task 6 summarization.');

manifest_bytes = fileread(manifest_file);
incomplete = manifest;
incomplete.creation_mode = 'execute';
incomplete.mode = 'execute';
incomplete.status = 'incomplete';
incomplete = resign_manifest(incomplete);
write_text(manifest_file, jsonencode(incomplete));
assert(strcmp(summarize_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:runNotSummarizable'), ...
    'Incomplete executed capsules must not be summarized.');
incomplete.status = 'complete';
incomplete = resign_manifest(incomplete);
write_text(manifest_file, jsonencode(incomplete));
assert(strcmp(summarize_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:runNotSummarizable'), ...
    'Complete status cannot bypass missing active fit artifacts.');
write_text(manifest_file, manifest_bytes);

activation_fixture = manifest;
activation_fixture.creation_mode = 'execute';
activation_fixture.mode = 'execute';
activation_fixture.status = 'incomplete';
activation_fixture = resign_manifest(activation_fixture);
write_text(manifest_file, jsonencode(activation_fixture));
decision_file = fullfile(run_dir, 'tables', ...
    'adaptive_restart_decision.json');
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionMissing'), ...
    'Optional restarts must require Task 6''s decision file.');
write_decision(decision_file, false, ...
    {struct('id', 'shared_by_genotype__Control', 'reason', 'test')});
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionRejected'), ...
    'A decision with activate=false must reject optional restarts.');
write_decision_value(decision_file, 0, ...
    {struct('id', 'shared_by_genotype__Control', 'reason', 'test')});
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionRejected'), ...
    'A numeric activate=0 decision must reject optional restarts.');
write_decision_value(decision_file, 2, ...
    {struct('id', 'shared_by_genotype__Control', 'reason', 'test')});
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionRejected'), ...
    'A numeric activate value other than 1 must reject optional restarts.');
write_decision_value(decision_file, [true true], ...
    {struct('id', 'shared_by_genotype__Control', 'reason', 'test')});
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionRejected'), ...
    'A nonscalar logical activate value must reject optional restarts.');
write_decision_value(decision_file, 1, ...
    {struct('id', 'not_a_manifest_group', 'reason', 'test')});
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionUnknownGroup'), ...
    'Numeric scalar activate=1 must remain accepted for compatibility.');
write_decision(decision_file, true, ...
    {struct('id', 'not_a_manifest_group', 'reason', 'test')});
assert(contains(fileread(decision_file), '"activate":true'), ...
    'Adaptive decision fixture must exercise a canonical JSON boolean.');
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveDecisionUnknownGroup'), ...
    'A decision naming a non-manifest group must be rejected.');
write_decision(decision_file, true, ...
    {struct('id', 'shared_by_genotype__Control', ...
    'reason', 'restart spread exceeds threshold')});
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveBaseIncomplete'), ...
    'Optional restarts must require every base fit to be complete and valid.');
delete(decision_file);
write_text(manifest_file, manifest_bytes);

config_file = fullfile(configs(1).folder, configs(1).name);
config_bytes = fileread(config_file);
write_text(config_file, [config_bytes ' ']);
config_mismatch_id = resume_identifier(run_id, output_root);
assert(strcmp(config_mismatch_id, 'mava_run_manifest:resumeMismatch'), ...
    'A tampered materialized config must fail resume by exact SHA identity.');
write_text(config_file, config_bytes);

target_file = fullfile(run_dir, 'data', 'shared_by_genotype', ...
    'ctrl_acute_target.txt');
target_bytes = fileread(target_file);
write_text(target_file, [target_bytes newline]);
data_mismatch_id = resume_identifier(run_id, output_root);
assert(strcmp(data_mismatch_id, 'mava_run_manifest:resumeMismatch'), ...
    'A tampered prepared target must fail resume by exact SHA identity.');
write_text(target_file, target_bytes);

metrics_file = fullfile(run_dir, 'data', 'shared_by_genotype', ...
    'experimental_metrics.csv');
metrics_bytes = fileread(metrics_file);
write_text(metrics_file, [metrics_bytes newline]);
metrics_mismatch_id = resume_identifier(run_id, output_root);
assert(strcmp(metrics_mismatch_id, 'mava_run_manifest:resumeMismatch'), ...
    'A tampered prepared metrics table must fail resume by exact SHA identity.');
write_text(metrics_file, metrics_bytes);

duplicate_id = '';
try
    run_mava_sequential_analysis(run_id, 'dry_run', ...
        'output_root', output_root, 'restarts', 2, ...
        'max_fun_evals', 10);
catch ME
    duplicate_id = ME.identifier;
end
assert(strcmp(duplicate_id, 'mava_run_manifest:runExists'), ...
    'Duplicate dry-run ID must reject the existing capsule.');
assert(isequal(production_before, directory_snapshot(production_root)), ...
    'Temporary dry run wrote beneath the existing production output tree.');

execute_manifest = make_complete_execute_fixture(manifest);
write_text(manifest_file, jsonencode(execute_manifest));
decision_file = fullfile(run_dir, 'tables', ...
    'adaptive_restart_decision.json');
selected_group = 'shared_by_genotype__Control';
write_decision(decision_file, true, ...
    {struct('id', selected_group, ...
    'reason', 'restart spread exceeds threshold')});
first_required = find(cellfun(@(item) item.required, ...
    execute_manifest.inventory), 1);
tampered_model = fullfile(execute_manifest.inventory{first_required}.result_dir, ...
    'model_best.json');
model_bytes = fileread(tampered_model);
write_text(tampered_model, [model_bytes ' ']);
assert(strcmp(activate_optional_identifier(run_id, output_root), ...
    'run_mava_sequential_analysis:adaptiveBaseIncomplete'), ...
    'A tampered base artifact must block adaptive restart activation.');
write_text(tampered_model, model_bytes);

execute_manifest = loadjson(manifest_file);
execute_manifest = add_invalid_first_optional_config(execute_manifest);
write_text(manifest_file, jsonencode(execute_manifest));
[activation_result, activation_message] = ...
    activate_optional_identifier(run_id, output_root);
activated = loadjson(manifest_file);
assert(strcmp(activation_result, ...
    'run_mava_sequential_analysis:invalidConfig'), ...
    ['Selective activation fixture must stop before optimizer execution. ' ...
    'Got %s: %s'], activation_result, activation_message);
assert(isequal(activated.materialization.optional_final_restart_groups, ...
    {selected_group}) && activated.records_planned == 28, ...
    'Only the decision-listed group''s four optional records may activate.');
assert(strcmp(activated.materialization. ...
    optional_final_restart_decisions{1}.reason, ...
    'restart spread exceeds threshold'), ...
    'Activated manifest must preserve the exact Task 6 decision reason.');
assert(strcmp(activated.materialization.adaptive_restart_decision.sha256, ...
    mava_sha256(decision_file)), ...
    'Activated manifest must integrity-protect the Task 6 decision file.');
assert_inherited_resolved_seed(activated, selected_group, ...
    'plus_k50', [0.11 0.22 0.33 0.5]);

fprintf('PASS: isolated Mava sequential dry run\n');
end

function manifest = make_complete_execute_fixture(manifest)
manifest.creation_mode = 'execute';
manifest.mode = 'execute';
manifest.status = 'complete';
manifest.records_planned = sum(cellfun(@(item) item.required, ...
    manifest.inventory));
for i = 1:numel(manifest.inventory)
    item = manifest.inventory{i};
    if ~item.required, continue; end
    root = loadjson(item.config_file);
    opt = root.MyoSim_optimization;
    stage_index = find(strcmp({'k123','plus_k50','plus_k40','plus_k73'}, ...
        item.stage));
    if item.restart == 1 && stage_index > 1
        inherited = fixture_best_seed(stage_index - 1);
        start = [inherited 0.5];
        for p = 1:numel(opt.parameter)
            opt.parameter{p}.p_value = start(p);
        end
        root.MyoSim_optimization = opt;
        write_text(item.config_file, jsonencode(root));
    end
    config_seed = cellfun(@(parameter) parameter.p_value, opt.parameter);
    manifest.materialization.configs{i}.sha256 = ...
        mava_sha256(item.config_file);
    manifest.materialization.configs{i}.resolved_seed = config_seed;
    write_complete_result(item, opt, fixture_best_seed(stage_index));
end
manifest = resign_manifest(manifest);
end

function write_complete_result(item, opt, best_seed)
if ~isfolder(item.result_dir), mkdir(item.result_dir); end
model_file = fullfile(item.result_dir, 'model_best.json');
best_file = fullfile(item.result_dir, 'best_optimization.json');
fit_file = fullfile(item.result_dir, 'fit_results.json');
status_file = fullfile(item.result_dir, 'status.json');
write_text(model_file, jsonencode(struct('MyoSim_model', struct)));
for p = 1:numel(opt.parameter)
    opt.parameter{p}.p_value = best_seed(p);
end
write_text(best_file, jsonencode(struct('MyoSim_optimization', opt)));
write_text(fit_file, jsonencode(struct('best_error', item.restart)));
hashes = struct('model_best', mava_sha256(model_file), ...
    'best_optimization', mava_sha256(best_file), ...
    'fit_results', mava_sha256(fit_file));
status = struct( ...
    'alignment_policy', item.alignment_policy, ...
    'genotype', item.genotype, ...
    'stage', item.stage, ...
    'restart', item.restart, ...
    'config_file', item.config_file, ...
    'config_sha256', mava_sha256(item.config_file), ...
    'status', 'complete', ...
    'artifact_hashes', hashes);
write_text(status_file, jsonencode(status));
end

function seed = fixture_best_seed(stage_index)
seeds = { ...
    [0.11 0.22 0.33], ...
    [0.12 0.23 0.34 0.45], ...
    [0.13 0.24 0.35 0.46 0.57], ...
    [0.14 0.25 0.36 0.47 0.58 0.69]};
seed = seeds{stage_index};
end

function manifest = add_invalid_first_optional_config(manifest)
selected = cellfun(@(item) ~item.required && ...
    strcmp(item.alignment_policy, 'shared_by_genotype') && ...
    strcmp(item.genotype, 'Control') && ...
    strcmp(item.stage, 'plus_k73'), manifest.inventory);
index = find(selected, 1, 'first');
item = manifest.inventory{index};
source = cellfun(@(candidate) candidate.required && ...
    strcmp(candidate.alignment_policy, item.alignment_policy) && ...
    strcmp(candidate.genotype, item.genotype) && ...
    strcmp(candidate.stage, item.stage) && candidate.restart == 2, ...
    manifest.inventory);
source_item = manifest.inventory{find(source, 1)};
root = loadjson(source_item.config_file);
opt = root.MyoSim_optimization;
seed = mava_deterministic_start(numel(opt.parameter), item.restart, []);
for p = 1:numel(opt.parameter)
    opt.parameter{p}.p_value = seed(p);
end
opt.max_fun_evals = opt.max_fun_evals + 1;
opt.best_model_folder = item.result_dir;
opt.best_opt_file_string = fullfile(item.result_dir, ...
    'best_optimization.json');
opt.job{1}.model_file_string = fullfile(item.result_dir, 'model_worker.json');
opt.job{1}.results_file_string = fullfile(item.result_dir, 'twitch.myo');
root.MyoSim_optimization = opt;
if ~isfolder(fileparts(item.config_file)), mkdir(fileparts(item.config_file)); end
if ~isfolder(item.result_dir), mkdir(item.result_dir); end
write_text(item.config_file, jsonencode(root));
manifest.materialization.configs{index}.sha256 = ...
    mava_sha256(item.config_file);
manifest.materialization.configs{index}.resolved_seed = seed;
manifest = resign_manifest(manifest);
end

function assert_inherited_resolved_seed(manifest, group_id, stage, expected)
matches = cellfun(@(item) strcmp( ...
    sprintf('%s__%s', item.alignment_policy, item.genotype), group_id) && ...
    strcmp(item.stage, stage) && item.restart == 1, manifest.inventory);
index = find(matches);
assert(isscalar(index) && max(abs( ...
    manifest.materialization.configs{index}.resolved_seed - expected)) < 1e-12, ...
    'Later stage restart 1 did not retain inherited coordinates plus midpoint.');
end

function identifier = resume_identifier(run_id, output_root)
identifier = '';
try
    run_mava_sequential_analysis(run_id, 'resume', ...
        'output_root', output_root, 'restarts', 2, ...
        'max_fun_evals', 10);
catch ME
    identifier = ME.identifier;
end
end

function identifier = summarize_identifier(run_id, output_root)
identifier = '';
try
    run_mava_sequential_analysis(run_id, 'summarize', ...
        'output_root', output_root, 'restarts', 2, ...
        'max_fun_evals', 10);
catch ME
    identifier = ME.identifier;
end
end

function [identifier, message] = activate_optional_identifier(run_id, output_root)
identifier = '';
message = '';
try
    run_mava_sequential_analysis(run_id, 'resume', ...
        'output_root', output_root, 'restarts', 2, ...
        'max_fun_evals', 10, ...
        'activate_optional_final_restarts', true);
catch ME
    identifier = ME.identifier;
    message = ME.message;
end
end

function write_decision(file, activate, groups)
write_decision_value(file, logical(activate), groups);
end

function write_decision_value(file, activate, groups)
parent = fileparts(file);
if ~isfolder(parent), mkdir(parent); end
decision = struct('schema_version', 1, ...
    'activate', activate, 'groups', {groups});
write_text(file, jsonencode(decision));
end

function manifest = resign_manifest(manifest)
inputs = struct( ...
    'schema_version', manifest.schema_version, ...
    'run_id', manifest.run_id, ...
    'run_dir', manifest.run_dir, ...
    'repository_root', manifest.repository_root, ...
    'hashes', manifest.hashes, ...
    'settings', manifest.settings, ...
    'groups', {manifest.groups}, ...
    'stages', {manifest.stages}, ...
    'inventory', {manifest.inventory});
immutable = inputs;
immutable.created_at = manifest.created_at;
immutable.repository_head = manifest.repository_head;
immutable.matlab_version = manifest.matlab_version;
immutable.creation_mode = manifest.creation_mode;
state = struct('mode', manifest.mode, 'status', manifest.status, ...
    'records_planned', manifest.records_planned);
manifest.input_signature = test_signature(inputs);
manifest.immutable_signature = test_signature(immutable);
manifest.materialization_signature = ...
    test_signature(manifest.materialization);
manifest.state_signature = test_signature(state);
end

function signature = test_signature(value)
bytes = unicode2native(jsonencode(value), 'UTF-8');
engine = java.security.MessageDigest.getInstance('SHA-256');
engine.update(bytes);
raw_digest = typecast(engine.digest(), 'uint8');
signature = lower(reshape(dec2hex(raw_digest, 2).', 1, []));
end

function write_text(file, value)
fid = fopen(file, 'w');
assert(fid >= 0, 'Could not write capsule tampering fixture.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s', value);
clear cleanup;
end

function snapshot = directory_snapshot(root)
if ~isfolder(root)
    snapshot = {};
    return;
end
items = dir(fullfile(root, '**', '*'));
snapshot = cell(numel(items), 1);
for i = 1:numel(items)
    relative = erase(fullfile(items(i).folder, items(i).name), [root filesep]);
    snapshot{i} = sprintf('%s|%d|%d|%.12f', relative, items(i).isdir, ...
        items(i).bytes, items(i).datenum);
end
snapshot = sort(snapshot);
end

function remove_if_present(path)
if isfolder(path), rmdir(path, 's'); end
end
