function test_mava_parameter_stages
% Nested stages and deterministic starts must remain exact and reproducible.

repo_root = fullfile(fileparts(mfilename('fullpath')), '..', '..');
addpath(fullfile(repo_root, 'Code', 'Fitting', 'mava_codex'));

stages = mava_parameter_stages();
assert(isequal({stages.id}, ...
    {'k123','plus_k50','plus_k40','plus_k73'}), ...
    'Sequential stage identifiers changed.');
assert(isequal(stages(1).parameters, {'k_1','k_2','k_3'}), ...
    'The first stage must independently fit k_1, k_2, and k_3.');
assert(isequal(stages(2).parameters, ...
    {'k_1','k_2','k_3','k_5_0'}), ...
    'The second stage must add only k_5_0.');
assert(isequal(stages(3).parameters, ...
    {'k_1','k_2','k_3','k_5_0','k_4_0'}), ...
    'The third stage must add only k_4_0.');
assert(isequal(stages(4).parameters, ...
    {'k_1','k_2','k_3','k_5_0','k_4_0','k_7_3'}), ...
    'The final stage must add only k_7_3.');
for i = 2:numel(stages)
    assert(isequal(stages(i).parameters(1:end-1), ...
        stages(i-1).parameters), 'Stages must be strictly nested.');
end

assert(isequal(mava_deterministic_start(3, 1, []), [0.5 0.5 0.5]), ...
    'Stage-1 restart 1 must use midpoint coordinates.');
previous_best = [0.12 0.34 0.56];
assert(isequal(mava_deterministic_start(4, 1, previous_best), ...
    [0.12 0.34 0.56 0.5]), ...
    'Later restart 1 must inherit prior coordinates and midpoint additions.');
assert(isequal(mava_deterministic_start(5, 1, previous_best), ...
    [0.12 0.34 0.56 0.5 0.5]), ...
    'Restart 1 must midpoint every newly added coordinate.');

expected_r2 = [0.57082039325 0.219348530672 0.467876668094 0.716404805516];
expected_r3 = [0.3416407865 0.590168923922 0.238697061344 0.487225198766];
actual_r2 = mava_deterministic_start(4, 2, []);
actual_r3 = mava_deterministic_start(4, 3, []);
assert(max(abs(actual_r2 - expected_r2)) < 1e-12, ...
    'Restart 2 does not match the specified deterministic sequence.');
assert(max(abs(actual_r3 - expected_r3)) < 1e-12, ...
    'Restart 3 does not match the specified deterministic sequence.');
assert(isequal(actual_r2, mava_deterministic_start(4, 2, [])), ...
    'Repeated deterministic starts must be bit-for-bit reproducible.');
assert(any(abs(actual_r2 - actual_r3) > 0.01), ...
    'Different restart indices must produce distinct starts.');

fprintf('PASS: Mava parameter stages and deterministic starts\n');
end
