function test_mava_feature_analysis
repo_root = fullfile(fileparts(mfilename('fullpath')), '..', '..');
addpath(fullfile(repo_root, 'Code', 'Fitting', 'mava_codex'));
workbook = fullfile(repo_root, 'Code', 'System', 'experimental_data', ...
    'Mava data.xlsx');
out_dir = tempname;
mkdir(out_dir);
cleanup = onCleanup(@() rmdir(out_dir, 's')); %#ok<NASGU>

features = mava_feature_analysis(workbook, out_dir);
assert(height(features) == 6, ...
    'The current workbook should yield six condition traces.');
assert(all(ismember({'peak_amplitude','rise_20_to_50', ...
    'relaxation_90_time','auc_to_relax50_normalized'}, ...
    features.Properties.VariableNames)), ...
    'Feature table is missing required fitting metrics.');
assert(all(isfinite(features.peak_amplitude)) && ...
    all(features.peak_amplitude > 0), ...
    'All six traces must have a positive robust amplitude.');
assert(isfile(fullfile(out_dir, 'mava_twitch_features.csv')) && ...
    isfile(fullfile(out_dir, 'mava_twitch_feature_group_summary.csv')) && ...
    isfile(fullfile(out_dir, 'feature_dictionary.txt')) && ...
    isfile(fullfile(out_dir, 'mava_feature_overview.png')), ...
    'Feature analysis did not materialize all review artifacts.');

fprintf('PASS: Mava feature analysis\n');
end
