function test_run_mava_sequential_dry_run
% Dry runs must build a complete isolated 3x4x2 capsule without fitting.

repo_root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(genpath(fullfile(repo_root, 'Code', 'System')));
addpath(fullfile(repo_root, 'Code', 'Fitting', 'mava_codex'));
output_root = tempname;
mkdir(output_root);
cleanup = onCleanup(@() remove_if_present(output_root));
run_id = sprintf('task5_dry_%s_%06d', char(datetime('now', ...
    'Format', 'yyyyMMdd''T''HHmmssSSS')), randi(999999));
production_root = fullfile(repo_root, 'Code', 'Fitting', 'mava_codex', ...
    'output');
production_before = directory_snapshot(production_root);

run = run_mava_sequential_analysis(run_id, 'dry_run', ...
    'output_root', output_root, 'restarts', 2, ...
    'max_fun_evals', 10);
run_dir = fullfile(output_root, run_id);
assert(strcmp(run.run_dir, run_dir) && isfolder(run_dir), ...
    'Dry run did not return and create the requested isolated capsule.');

manifest_file = fullfile(run_dir, 'manifest.json');
manifest = loadjson(manifest_file);
assert(strcmp(manifest.run_id, run_id) && ...
    strcmp(manifest.mode, 'dry_run') && ...
    strcmp(manifest.status, 'dry_run_complete'), ...
    'Dry run manifest identity or terminal status is wrong.');
assert(manifest.settings.fit_start_index == 481 && ...
    manifest.settings.restarts == 2 && ...
    manifest.settings.extra_final_restarts == 4 && ...
    manifest.settings.max_fun_evals == 10 && ...
    abs(manifest.settings.tol_fun - 1e-5) < eps && ...
    abs(manifest.settings.tol_x - 1e-3) < eps && ...
    strcmp(manifest.settings.scale_mode, 'peak'), ...
    'Dry run manifest omitted or changed requested/default controls.');
assert(isfield(manifest, 'repository_head') && ...
    numel(manifest.repository_head) == 40 && ...
    isfield(manifest, 'matlab_version') && ...
    isfield(manifest, 'created_at'), ...
    'Dry run manifest omitted environment provenance.');
assert(isfield(manifest.hashes, 'workbook') && ...
    isfield(manifest.hashes, 'protocol') && ...
    isfield(manifest.hashes, 'baseline_templates') && ...
    isfield(manifest.hashes, 'options') && ...
    numel(manifest.hashes.sources) >= 8, ...
    'Dry run manifest omitted required input or source hashes.');

assert(numel(manifest.groups) == 2, ...
    'Manifest must retain the two requested alignment groups.');
assert(strcmp(manifest.groups{1}.policy, 'shared_by_genotype') && ...
    isequal(manifest.groups{1}.genotypes, {'Control','H251N'}) && ...
    strcmp(manifest.groups{2}.policy, 'independent_trace') && ...
    isequal(manifest.groups{2}.genotypes, {'Control'}), ...
    'Manifest alignment groups are not the required three comparisons.');
expected_stage_ids = {'k123','plus_k50','plus_k40','plus_k73'};
assert(numel(manifest.stages) == 4 && ...
    isequal(cellfun(@(s) s.id, manifest.stages, ...
    'UniformOutput', false), expected_stage_ids), ...
    'Manifest stage IDs or order changed.');

assert(isfile(fullfile(run_dir, 'data', 'shared_by_genotype', ...
    'experimental_metrics.csv')) && ...
    isfile(fullfile(run_dir, 'data', 'independent_trace', ...
    'experimental_metrics.csv')), ...
    'Dry run did not preprocess every requested alignment policy.');

configs = dir(fullfile(run_dir, 'configs', '*.json'));
assert(numel(configs) == 24, ...
    'Two-restart dry run must create exactly 3 x 4 x 2 = 24 configs.');
assert(numel(unique({configs.name})) == 24, ...
    'Every dry-run config filename must be unique.');
for i = 1:numel(configs)
    loaded = loadjson(fullfile(configs(i).folder, configs(i).name));
    opt = loaded.MyoSim_optimization;
    names = cellfun(@(p) p.name, opt.parameter, 'UniformOutput', false);
    assert(any(strcmp(names, 'k_2')), ...
        'Each sequential config must contain ordinary free k_2.');
    assert(~isfield(opt, 'constraint') && ...
        ~isfield(opt, 'k_2_k_1_ratio'), ...
        'Sequential configs must not reintroduce a k_2 ratio constraint.');
    assert(opt.job{1}.fit_start_index == 481, ...
        'Every dry-run config must use row 481 as the first fit row.');
end

statuses = dir(fullfile(run_dir, 'results', '**', 'status.json'));
assert(numel(statuses) == 24, ...
    'Every planned result must have a status.json.');
for i = 1:numel(statuses)
    status = loadjson(fullfile(statuses(i).folder, statuses(i).name));
    assert(strcmp(status.status, 'planned'), ...
        'Dry-run result status must remain planned, not complete.');
end
fitted_models = dir(fullfile(run_dir, '**', 'model_best.json'));
assert(isempty(fitted_models), ...
    'Dry run must not create fitted model_best.json files.');

duplicate_id = '';
try
    run_mava_sequential_analysis(run_id, 'dry_run', ...
        'output_root', output_root, 'restarts', 2, ...
        'max_fun_evals', 10);
catch ME
    duplicate_id = ME.identifier;
end
assert(strcmp(duplicate_id, 'mava_run_manifest:runExists'), ...
    'Duplicate dry-run ID must reject the existing capsule.');
assert(isequal(production_before, directory_snapshot(production_root)), ...
    'Temporary dry run wrote beneath the existing production output tree.');

fprintf('PASS: isolated Mava sequential dry run\n');
end

function snapshot = directory_snapshot(root)
if ~isfolder(root)
    snapshot = {};
    return;
end
items = dir(fullfile(root, '**', '*'));
snapshot = cell(numel(items), 1);
for i = 1:numel(items)
    relative = erase(fullfile(items(i).folder, items(i).name), [root filesep]);
    snapshot{i} = sprintf('%s|%d|%d|%.12f', relative, items(i).isdir, ...
        items(i).bytes, items(i).datenum);
end
snapshot = sort(snapshot);
end

function remove_if_present(path)
if isfolder(path), rmdir(path, 's'); end
end
