function artifacts = mava_summary_artifact_inventory(run_dir)
% Return the exact required summary/publication artifact inventory.

run_dir = char(string(run_dir));
specification = { ...
    'restart_summary','table',fullfile('tables','restart_summary.csv'); ...
    'stage_summary','table',fullfile('tables','stage_summary.csv'); ...
    'boundary_diagnostics','table',fullfile('tables','boundary_diagnostics.csv'); ...
    'waveform_metrics','table',fullfile('tables','waveform_metrics.csv'); ...
    'identifiability_summary','table',fullfile('tables','identifiability_summary.csv'); ...
    'experimental_traces_and_alignment','image',fullfile('figures','experimental_traces_and_alignment.png'); ...
    'k123_fit_evidence','image',fullfile('figures','k123_failed_fits.png'); ...
    'sequential_error_aic','image',fullfile('figures','sequential_error_aic.png'); ...
    'best_fit_waveforms','image',fullfile('figures','best_fit_waveforms.png'); ...
    'boundary_identifiability','image',fullfile('figures','boundary_identifiability.png'); ...
    'authority_note','note','AUTHORITATIVE_OUTPUTS.md'; ...
    'adaptive_restart_decision','decision',fullfile('tables','adaptive_restart_decision.json')};
artifacts = cell(1,size(specification,1));
for i = 1:size(specification,1)
    artifacts{i} = struct('id', specification{i,1}, ...
        'kind', specification{i,2}, ...
        'path', fullfile(run_dir, specification{i,3}), 'sha256', '');
end
end
