function stages = mava_parameter_stages
% Return the exact nested parameter stages for the Mava analysis.

stages(1) = struct('id', 'k123', ...
    'parameters', {{'k_1','k_2','k_3'}});
stages(2) = struct('id', 'plus_k50', ...
    'parameters', {{'k_1','k_2','k_3','k_5_0'}});
stages(3) = struct('id', 'plus_k40', ...
    'parameters', {{'k_1','k_2','k_3','k_5_0','k_4_0'}});
stages(4) = struct('id', 'plus_k73', ...
    'parameters', {{'k_1','k_2','k_3','k_5_0','k_4_0','k_7_3'}});
end
