function mava_validate_summary_materialization(manifest)
% Fail closed unless signed summary artifacts match the current result set.

if ~isfield(manifest.materialization, 'summary')
    error('mava_validate_summary_materialization:badSchema', ...
        'Manifest has no summary materialization.');
end
summary = manifest.materialization.summary;
required = {'state','active_result_fingerprint','artifacts','published'};
if ~isstruct(summary) || ~isscalar(summary) || ...
        ~isequal(sort(fieldnames(summary)), sort(required(:))) || ...
        ~(islogical(summary.published) && isscalar(summary.published))
    error('mava_validate_summary_materialization:badSchema', ...
        'Summary materialization has an invalid schema.');
end
expected = mava_summary_artifact_inventory(manifest.run_dir);
if ~iscell(summary.artifacts) || numel(summary.artifacts) ~= numel(expected)
    error('mava_validate_summary_materialization:badSchema', ...
        'Summary artifact inventory is incomplete.');
end
for i = 1:numel(expected)
    item = summary.artifacts{i};
    fields = {'id','kind','path','sha256'};
    if ~isstruct(item) || ~isscalar(item) || ...
            ~isequal(sort(fieldnames(item)), sort(fields(:))) || ...
            ~strcmp(char(string(item.id)), expected{i}.id) || ...
            ~strcmp(char(string(item.kind)), expected{i}.kind) || ...
            ~strcmp(char(string(item.path)), expected{i}.path)
        error('mava_validate_summary_materialization:badSchema', ...
            'Summary artifact identity %d does not match the capsule layout.', i);
    end
end

state = char(string(summary.state));
if strcmp(state, 'none')
    if ~isempty(summary.active_result_fingerprint) || summary.published || ...
            any(cellfun(@(item) ~isempty(item.sha256), summary.artifacts))
        error('mava_validate_summary_materialization:badState', ...
            'An unmaterialized summary must not retain hashes or publication.');
    end
    return;
end
if ~ismember(state, {'provisional_optional_requested','final'})
    error('mava_validate_summary_materialization:badState', ...
        'Unknown summary state: %s.', state);
end
fingerprint = mava_active_result_fingerprint(manifest);
if ~strcmp(char(string(summary.active_result_fingerprint)), fingerprint)
    error('mava_validate_summary_materialization:staleSummary', ...
        'Summary fingerprint does not match the active result set.');
end
for i = 1:numel(summary.artifacts)
    item = summary.artifacts{i};
    hash = char(string(item.sha256));
    if isempty(regexp(hash, '^[0-9a-f]{64}$', 'once')) || ...
            ~isfile(item.path) || ~strcmp(mava_sha256(item.path), hash)
        error('mava_validate_summary_materialization:hashMismatch', ...
            'Summary artifact hash mismatch: %s.', item.path);
    end
    validate_artifact(item);
end

decision_entry = summary.artifacts{cellfun(@(item) ...
    strcmp(item.id,'adaptive_restart_decision'), summary.artifacts)};
decision = loadjson(decision_entry.path);
selected = cellstr(string( ...
    manifest.materialization.optional_final_restart_groups));
if strcmp(state, 'provisional_optional_requested')
    if ~decision_true(decision) || isempty(decision.groups) || ...
            ~isempty(selected) || summary.published
        error('mava_validate_summary_materialization:badState', ...
            'Provisional summary state does not match its adaptive decision.');
    end
else
    if decision_true(decision)
        groups = as_cells(decision.groups);
        ids = cellfun(@(item) char(string(item.id)), groups, ...
            'UniformOutput', false);
        if isempty(selected) || ~isequal(ids, selected)
            error('mava_validate_summary_materialization:badState', ...
                'Final summary does not match activated optional groups.');
        end
    elseif ~isempty(selected)
        error('mava_validate_summary_materialization:badState', ...
            'Final no-activation decision conflicts with selected groups.');
    end
end
end

function validate_artifact(item)
switch char(string(item.kind))
    case 'table'
        T = readtable(item.path, 'TextType', 'string');
        required = required_table_columns(char(string(item.id)));
        if height(T) < 1 || ~isequal(T.Properties.VariableNames, required)
            error('mava_validate_summary_materialization:invalidArtifact', ...
                'Summary table has an empty or unexpected schema: %s.', ...
                item.path);
        end
        validate_table_content(char(string(item.id)), T, item.path);
    case 'image'
        info = dir(item.path);
        fid = fopen(item.path, 'r');
        cleanup = onCleanup(@() fclose(fid));
        magic = fread(fid,8,'*uint8')';
        if info.bytes <= 1000 || ~isequal(magic, ...
                uint8([137 80 78 71 13 10 26 10]))
            error('mava_validate_summary_materialization:invalidArtifact', ...
                'Summary image is empty or not PNG: %s.', item.path);
        end
    case 'note'
        text = fileread(item.path);
        if isempty(strtrim(text)) || ~contains(text, 'independently fitted `k_2`') || ...
                ~contains(text, 'practical identifiability', 'IgnoreCase', true)
            error('mava_validate_summary_materialization:invalidArtifact', ...
                'Authority note is incomplete.');
        end
    case 'decision'
        decision = loadjson(item.path);
        if ~isstruct(decision) || ~isscalar(decision) || ...
                ~isequal(sort(fieldnames(decision)), ...
                {'activate';'groups';'schema_version'}) || ...
                ~isscalar(decision.schema_version) || decision.schema_version ~= 1 || ...
                ~valid_boolean(decision.activate) || ...
                ~valid_decision_groups(decision.groups)
            error('mava_validate_summary_materialization:invalidArtifact', ...
                'Adaptive decision has an invalid schema.');
        end
    otherwise
        error('mava_validate_summary_materialization:badSchema', ...
            'Unknown summary artifact kind.');
end
end

function required = required_table_columns(id)
switch id
    case 'restart_summary'
        required = {'id','group_id','alignment_policy','genotype','stage', ...
            'restart','completed','converged','best_error','AIC', ...
            'n_free_params','exitflag','iterations','func_count', ...
            'boundary_hit','within_stage_delta_AIC'};
    case 'stage_summary'
        required = {'group_id','alignment_policy','genotype','stage', ...
            'completed_starts','converged_starts','representative_id', ...
            'representative_restart','defensible','best_error', ...
            'median_error','worst_error','best_AIC','near_optimal_starts', ...
            'solution_clusters','delta_AIC','akaike_weight'};
    case 'boundary_diagnostics'
        required = {'id','group_id','alignment_policy','genotype','stage', ...
            'restart','name','p_raw','p_simulated','normalized_distance', ...
            'physical_distance','log_distance','fold_distance','lower_bound', ...
            'upper_bound','physical_value','classification'};
    case 'waveform_metrics'
        required = {'id','group_id','alignment_policy','genotype','stage', ...
            'restart','target_peak','target_force_rise_time', ...
            'target_calcium_to_force_lag','target_time_to_peak_argmax', ...
            'target_time_to_peak_centroid','target_relax_half_time', ...
            'target_fwhm','target_normalized_rmse','model_peak', ...
            'model_relative_peak_error_signed','model_force_rise_time', ...
            'model_calcium_to_force_lag','model_time_to_peak_argmax', ...
            'model_time_to_peak_centroid','model_relax_half_time', ...
            'model_fwhm','model_normalized_rmse'};
    case 'identifiability_summary'
        required = {'group_id','alignment_policy','genotype','stage', ...
            'parameter','completed_starts','converged_starts','best_error', ...
            'median_error','worst_error','near_optimal_starts', ...
            'solution_clusters','log10_spread_all', ...
            'log10_spread_near_optimal','near_optimal_fold_spread', ...
            'boundary_frequency','classification'};
    otherwise
        required = {};
end
end

function validate_table_content(id, T, file)
if isempty(required_table_columns(id))
    error('mava_validate_summary_materialization:invalidArtifact', ...
        'Unknown summary table: %s.', file);
end
switch id
    case 'restart_summary'
        valid = numel(unique(T.id)) == height(T) && ...
            all(T.completed == 1) && ...
            all(T.converged == (isfinite(T.exitflag) & T.exitflag > 0));
    case 'stage_summary'
        keys = T.group_id + "__" + T.stage;
        valid = numel(unique(keys)) == height(T) && ...
            all(T.completed_starts >= T.converged_starts) && ...
            all(T.converged_starts >= 0) && ...
            all(T.near_optimal_starts <= T.converged_starts) && ...
            all(isfinite(T.akaike_weight)) && ...
            all(T.akaike_weight >= 0 & T.akaike_weight <= 1) && ...
            group_weights_sum_to_one(T);
    case 'boundary_diagnostics'
        allowed = ["outside_lower","outside_upper","near_lower", ...
            "near_upper","interior"];
        valid = all(ismember(string(T.classification), allowed)) && ...
            all(isfinite(T.p_raw)) && all(isfinite(T.p_simulated)) && ...
            all(isfinite(T.physical_distance)) && ...
            all(T.upper_bound > T.lower_bound);
    case 'waveform_metrics'
        valid = all(T.target_normalized_rmse == 0) && ...
            all(T.model_normalized_rmse >= 0 | isnan(T.model_normalized_rmse));
    case 'identifiability_summary'
        allowed = ["stable","weak","non-identifiable"];
        valid = all(ismember(string(T.classification), allowed)) && ...
            all(T.completed_starts >= T.converged_starts) && ...
            all(T.near_optimal_starts <= T.converged_starts) && ...
            all(T.boundary_frequency >= 0 & T.boundary_frequency <= 1);
    otherwise
        valid = false;
end
if ~valid
    error('mava_validate_summary_materialization:invalidArtifact', ...
        'Summary table has invalid content: %s.', file);
end
end

function tf = group_weights_sum_to_one(T)
groups = unique(T.group_id);
tf = true;
for i = 1:numel(groups)
    rows = T.group_id == groups(i);
    tf = tf && abs(sum(T.akaike_weight(rows))-1) <= 1e-10;
end
end

function tf = valid_boolean(value)
tf = (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isreal(value) && isscalar(value) && ...
    ismember(value,[0 1]));
end

function tf = valid_decision_groups(value)
groups = as_cells(value);
ids = strings(1,numel(groups));
tf = true;
for i = 1:numel(groups)
    group = groups{i};
    tf = tf && isstruct(group) && isscalar(group) && ...
        isequal(sort(fieldnames(group)), {'id';'reason'}) && ...
        (ischar(group.id) || (isstring(group.id) && isscalar(group.id))) && ...
        strlength(string(group.id)) > 0 && ...
        (ischar(group.reason) || ...
        (isstring(group.reason) && isscalar(group.reason))) && ...
        strlength(string(group.reason)) > 0;
    if ~tf, return; end
    ids(i) = string(group.id);
end
tf = numel(unique(ids)) == numel(ids);
end

function tf = decision_true(decision)
tf = (islogical(decision.activate) && isscalar(decision.activate) && ...
    decision.activate) || (isnumeric(decision.activate) && ...
    isreal(decision.activate) && isscalar(decision.activate) && ...
    decision.activate == 1);
end

function cells = as_cells(value)
if iscell(value), cells = value;
elseif isstruct(value), cells = num2cell(value);
elseif isempty(value), cells = {};
else, cells = {value};
end
end
